/**
 * DIY Mode Static Content
 * Sample products and avatars for the DIY creation flow
 */

import type { Product, Avatar } from '@/types'

// Sample Products for DIY Mode
export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Nike Air Max 90',
    image: '/images/products/nike-shoe.svg',
    source: 'url',
    url: 'https://example.com/products/nike-air-max',
    description: 'Classic sneaker with visible Air cushioning that revolutionized the sneaker industry.',
    features: ['Visible Air unit for cushioning', 'Leather and mesh upper', 'Rubber outsole for durability', 'Iconic design since 1990'],
    price: 129.99,
  },
  {
    id: 'prod_2',
    name: 'Smart Watch Pro',
    image: '/images/products/smart-watch.svg',
    source: 'url',
    url: 'https://example.com/products/smart-watch-pro',
    description: 'Advanced fitness tracking smartwatch with health monitoring features.',
    features: ['Heart rate monitor', 'GPS tracking', '7-day battery life', 'Water resistant 50m', 'Sleep tracking'],
    price: 199.99,
  },
  {
    id: 'prod_3',
    name: 'Wireless Headphones',
    image: '/images/products/headphones.svg',
    source: 'url',
    url: 'https://example.com/products/headphones',
    description: 'Premium noise-canceling headphones with studio-quality sound.',
    features: ['Active noise cancellation', '30hr battery life', 'Premium audio drivers', 'Comfortable over-ear design', 'Bluetooth 5.0'],
    price: 299.99,
  },
  {
    id: 'prod_4',
    name: 'Phone Mount Ultra',
    image: '/images/products/phone-mount.svg',
    source: 'manual',
    description: 'Universal car phone mount with strong magnetic hold.',
    features: ['360° rotation', 'One-hand operation', 'Strong magnetic grip', 'Universal compatibility', 'Easy installation'],
    price: 24.99,
  },
  {
    id: 'prod_5',
    name: 'Fitness Tracker Band',
    image: '/images/products/fitness-band.svg',
    source: 'url',
    url: 'https://example.com/products/fitness-tracker',
    description: 'Slim fitness tracker with comprehensive health monitoring.',
    features: ['24/7 heart rate', 'Step counter', 'Sleep analysis', 'Water resistant', '14-day battery'],
    price: 49.99,
  },
  {
    id: 'prod_6',
    name: 'Portable Blender',
    image: '/images/products/blender.svg',
    source: 'url',
    url: 'https://example.com/products/blender',
    description: 'Compact portable blender for smoothies on the go.',
    features: ['USB rechargeable', '6 blades', 'BPA-free', '380ml capacity', 'Self-cleaning'],
    price: 34.99,
  },
]

// Sample Avatars for DIY Mode
export const SAMPLE_AVATARS: Avatar[] = [
  {
    id: 'avatar_1',
    name: 'Sarah',
    image: '/images/avatars/sarah.svg',
    videoPreview: '/videos/avatars/sarah-preview.mp4',
    style: 'energetic',
    gender: 'female',
    isPremium: false,
    voiceSample: '/audio/sarah-sample.mp3',
  },
  {
    id: 'avatar_2',
    name: 'Michael',
    image: '/images/avatars/michael.svg',
    videoPreview: '/videos/avatars/michael-preview.mp4',
    style: 'professional',
    gender: 'male',
    isPremium: false,
    voiceSample: '/audio/michael-sample.mp3',
  },
  {
    id: 'avatar_3',
    name: 'Emma',
    image: '/images/avatars/emma.svg',
    videoPreview: '/videos/avatars/emma-preview.mp4',
    style: 'casual',
    gender: 'female',
    isPremium: false,
    voiceSample: '/audio/emma-sample.mp3',
  },
  {
    id: 'avatar_4',
    name: 'James',
    image: '/images/avatars/james.svg',
    videoPreview: '/videos/avatars/james-preview.mp4',
    style: 'energetic',
    gender: 'male',
    isPremium: true,
    voiceSample: '/audio/james-sample.mp3',
  },
  {
    id: 'avatar_5',
    name: 'Sophia',
    image: '/images/avatars/sophia.svg',
    videoPreview: '/videos/avatars/sophia-preview.mp4',
    style: 'professional',
    gender: 'female',
    isPremium: true,
    voiceSample: '/audio/sophia-sample.mp3',
  },
  {
    id: 'avatar_6',
    name: 'Alex',
    image: '/images/avatars/alex.svg',
    videoPreview: '/videos/avatars/alex-preview.mp4',
    style: 'casual',
    gender: 'neutral',
    isPremium: false,
    voiceSample: '/audio/alex-sample.mp3',
  },
  {
    id: 'avatar_7',
    name: 'Isabella',
    image: '/images/avatars/isabella.svg',
    videoPreview: '/videos/avatars/isabella-preview.mp4',
    style: 'energetic',
    gender: 'female',
    isPremium: true,
    voiceSample: '/audio/isabella-sample.mp3',
  },
  {
    id: 'avatar_8',
    name: 'David',
    image: '/images/avatars/david.svg',
    videoPreview: '/videos/avatars/david-preview.mp4',
    style: 'professional',
    gender: 'male',
    isPremium: false,
    voiceSample: '/audio/david-sample.mp3',
  },
]
